server {
    listen 80;
    root /usr/share/nginx/html;
    include /etc/nginx/mime.types;
    types {
        application/javascript mjs;
    }
    default_type application/octet-stream;
    index index.html;

    # All resources must not be cached so browsers always load the latest version
    # after a new deployment.
    location / {
        try_files $uri $uri/ /index.html;
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        add_header Pragma "no-cache";
        add_header Expires "0";
    }
}
