# Generated by Django 6.0.5 on 2026-09-13 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aiworks_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSession',
            fields=[
                ('session_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aiworks_core.session')),
                ('dilemma', models.TextField(blank=True)),
                ('compressed_context', models.TextField(blank=True)),
                ('compressed_file_content', models.TextField(blank=True)),
                ('prev_session', models.TextField(blank=True)),
                ('additional_user_comments', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'proxy': False,
            },
            bases=('aiworks_core.session',),
        ),
    ]
